/* Generated by AN DISI Unibo */ 
package it.unibo.serviceaccessgui

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Serviceaccessgui ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = false
						CommUtils.outmagenta("$name | start request")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t118",targetState="dostorefood",cond=whenDispatch("dostorefood"))
					transition(edgeName="t119",targetState="doinsertticket",cond=whenDispatch("doinsertticket"))
				}	 
				state("doinsertticket") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("ticketaccepted(TICKETCODE,TICKETSECRET,TIMESTAMP)"), Term.createTerm("ticketaccepted(TICKETCODE,TICKETSECRET,TIMESTAMP)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
											var Ticketcode= payloadArg(0);
											var Ticketsecret= payloadArg(1);
								CommUtils.outmagenta("$name | sneding ticket to coldstorageservice")
								request("sendticket", "sendticket($Ticketcode,$Ticketsecret)" ,"coldstorageservice" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("dostorefood") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("dostorefood(SESSIONNUMBER,KG)"), Term.createTerm("dostorefood(KG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
											var Kg= payloadArg(0);
											
						}
						request("storefood", "storefood($Kg)" ,"coldstorageservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t220",targetState="handlestorefoodresponse",cond=whenReply("ticketaccepted"))
					transition(edgeName="t221",targetState="handlestorefoodresponse",cond=whenReply("ticketdenied"))
				}	 
				state("handlestorefoodresponse") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("ticketaccepted(TICKETCODE,TICKETSECRET,TIMESTAMP)"), Term.createTerm("ticketaccepted(TICKETCODE,TICKETSECRET,TIMESTAMP)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
						}
						if( checkMsgContent( Term.createTerm("ticketdenied(ARG)"), Term.createTerm("ticketdenied(ok)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
}
