/* Generated by AN DISI Unibo */ 
package it.unibo.serviceaccessgui

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Serviceaccessgui ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 gui.GuiUtils.createGui(myself)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitticketrequest", cond=doswitch() )
				}	 
				state("waitticketrequest") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="handleticketrequest",cond=whenEvent("guicmd"))
				}	 
				state("handleticketrequest") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("guicmd(COMMAND,PARAMETER)"), Term.createTerm("guicmd(createticket,MASS)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CommUtils.outmagenta("request ticket creation") 
												Mass = payloadArg(1);
								request("createticket", "createticket($Mass)" ,"coldstorageservice" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t112",targetState="ticketaccepted",cond=whenReply("acceptticket"))
					transition(edgeName="t113",targetState="ticketdenied",cond=whenReply("denyticket"))
				}	 
				state("ticketaccepted") { //this:State
					action { //it:State
						 CommUtils.outgreen("ticket"+ticket)  
						if( checkMsgContent( Term.createTerm("acceptticket(ARG)"), Term.createTerm("acceptticket(TICKET)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												Ticket  = payloadArg(0);
												CommUtils.outmagenta("ticket: "+ Ticket); 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t114",targetState="handleticketfromuser",cond=whenEvent("guicmd"))
				}	 
				state("handleticketfromuser") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("guicmd(COMMAND,PARAMETER)"), Term.createTerm("guicmd(insertticket,TICKET)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CommUtils.outmagenta("insert ticket"); 
												Ticket  = payloadArg(1);
								forward("camionin", "camionin($Ticket)" ,"coldstorageservice" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitticketrequest", cond=doswitch() )
				}	 
				state("ticketdenied") { //this:State
					action { //it:State
						 CommUtils.outred("not enough space")  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitticketrequest", cond=doswitch() )
				}	 
			}
		}
}
